name: portfolio-guard
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Core Python ---
  - python=3.12
  - pip
  # --- Data Science Stack ---
  - pandas
  - scikit-learn
  - xgboost
  
  # --- Notebook & Development ---
  - jupyter
  
  # --- Pip-installed Packages ---
  # Conda will manage the pip installation
  - pip:
    - wandb
    - fastapi
    - uvicorn
    - google-generativeai
    - python-dotenv
    - alpha-vantage
    - requests
